### ISSUE TITLE
Лабораторная 2

### ISSUE THREAD

**Issue by poli-poli** [poli-poli/-2-#1]

**Comment by poli-poli** [comment]
[Станчук П.Н. ТКИ-311 Лаб. 2 (1).docx](https://github.com/pnstch/-2-/files/8148846/-311.2.1.docx)

**Comment by FlashAnton** [comment]
Дополните содержимым недостающие разделы, отмеченные красным.
Внесите правки в блок-схему алгоритма. Она содержит ошибки.
Дополните работу анализом быстродействия составленного алгоритма.

**Comment by FlashAnton** [comment]
Закрываем ветвь обсуждений.
